[package]
authors.workspace = true
categories = ["api-bindings", "data-structures"]
description = "API definitions for communication between Quantus node and external miners"
edition.workspace = true
homepage.workspace = true
keywords = [
	"api",
	"quantus-network",
	"substrate",
]
license.workspace = true
name = "qu-miner-api"
repository.workspace = true
version = "0.0.1"

[dependencies]
serde = { workspace = true, features = ["derive"] }
