// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_qpow`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-06-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Pro-4.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --pallet
// pallet-qpow
// --extrinsic
// *
// --template
// ./.maintain/frame-weight-template.hbs
// --output
// ./pallets/qpow/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_qpow`.
pub trait WeightInfo {
	fn on_finalize_max_history() -> Weight;
}

/// Weights for `pallet_qpow` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `QPoW::BlocksInPeriod` (r:1 w:1)
	/// Proof: `QPoW::BlocksInPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::CurrentDistanceThreshold` (r:1 w:1)
	/// Proof: `QPoW::CurrentDistanceThreshold` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockTime` (r:1 w:1)
	/// Proof: `QPoW::LastBlockTime` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::TotalWork` (r:1 w:1)
	/// Proof: `QPoW::TotalWork` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::HistoryIndex` (r:1 w:1)
	/// Proof: `QPoW::HistoryIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::HistorySize` (r:1 w:1)
	/// Proof: `QPoW::HistorySize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::BlockTimeHistory` (r:9 w:1)
	/// Proof: `QPoW::BlockTimeHistory` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::BlockDistanceThresholds` (r:0 w:1)
	/// Proof: `QPoW::BlockDistanceThresholds` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockDuration` (r:0 w:1)
	/// Proof: `QPoW::LastBlockDuration` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize_max_history() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `707`
		//  Estimated: `23445`
		// Minimum execution time: 213_000_000 picoseconds.
		Weight::from_parts(217_000_000, 23445)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `QPoW::BlocksInPeriod` (r:1 w:1)
	/// Proof: `QPoW::BlocksInPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::CurrentDistanceThreshold` (r:1 w:1)
	/// Proof: `QPoW::CurrentDistanceThreshold` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockTime` (r:1 w:1)
	/// Proof: `QPoW::LastBlockTime` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::TotalWork` (r:1 w:1)
	/// Proof: `QPoW::TotalWork` (`max_values`: Some(1), `max_size`: Some(64), added: 559, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::HistoryIndex` (r:1 w:1)
	/// Proof: `QPoW::HistoryIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::HistorySize` (r:1 w:1)
	/// Proof: `QPoW::HistorySize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::BlockTimeHistory` (r:9 w:1)
	/// Proof: `QPoW::BlockTimeHistory` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::BlockDistanceThresholds` (r:0 w:1)
	/// Proof: `QPoW::BlockDistanceThresholds` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `QPoW::LastBlockDuration` (r:0 w:1)
	/// Proof: `QPoW::LastBlockDuration` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize_max_history() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `707`
		//  Estimated: `23445`
		// Minimum execution time: 213_000_000 picoseconds.
		Weight::from_parts(217_000_000, 23445)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
}
